mutation createProduct($name: String!, $price: Int!, $brandId: Int!) {
    createProduct(
        name: $name,
        price: $price,
        brandId: $brandId
    ) {
        id
        name
        price
        brand {
            id
            name
        }
    }
}